version: '3.8'

services:
  telegram-bot:
    build: ./services/telegram-bot
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    volumes:
      - ./services/telegram-bot/src:/app # Bind mount for live development

  mops-crawler:
    build: ./services/mops-crawler
    restart: always
    networks:
      - tradewise-net
    volumes:
      - ./services/mops-crawler/src:/app # Bind mount for live development
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import http.client; conn = http.client.HTTPConnection('localhost', 80); conn.request('GET', '/health'); response = conn.getresponse(); assert response.status == 200\""]
      interval: 10s
      timeout: 6s
      retries: 5

  report-harvester:
    build: ./services/report-harvester
    restart: always
    networks:
      - tradewise-net
    depends_on:
      database-api:
        condition: service_healthy
      mops-crawler:
        condition: service_healthy
    volumes:
      - ./services/report-harvester/src:/app # Bind mount for live development

  fugle-market-data:
    build: ./services/fugle-market-data
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    volumes:
      - ./services/fugle-market-data/src:/app # Bind mount for live development

  fugle-trading:
    build: ./services/fugle-trading
    restart: always
    volumes:
      - ./services/fugle-trading/src:/app # Bind mount for live development
      - ./config/config.fugletrading.ini:/app/config.ini
      - ./config/cert.p12:/app/cert.p12
    networks:
      - tradewise-net

  order-manager:
    build: ./services/order-manager
    restart: always
    networks:
      - tradewise-net
    volumes:
      - ./services/order-manager/src:/app # Bind mount for live development

  insight-engine:
    build: ./services/insight-engine
    restart: always
    networks:
      - tradewise-net
    volumes:
      - ./services/insight-engine/src:/app # Bind mount for live development

  logging:
    build: ./services/logging
    restart: always
    networks:
      - tradewise-net
    volumes:
      - ./services/logging/src:/app # Bind mount for live development

  database:
    image: mongo
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    volumes:
      - db-data:/data/db

  database-api:
    build: ./services/database-api
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    depends_on:
      - database
    volumes:
      - ./services/database-api/src:/app # Bind mount for live development
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import http.client; conn = http.client.HTTPConnection('localhost', 80); conn.request('GET', '/health'); response = conn.getresponse(); assert response.status == 200\""]
      interval: 10s
      timeout: 6s
      retries: 5

networks:
  tradewise-net:
    driver: bridge

volumes:
  db-data:

