version: '3.8'

services:
  telegram-bot:
    build: ./services/telegram-bot
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net

  mops-crawler:
    build: ./services/mops-crawler
    restart: always
    networks:
      - tradewise-net
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import http.client; conn = http.client.HTTPConnection('localhost', 80); conn.request('GET', '/health'); response = conn.getresponse(); assert response.status == 200\""]
      interval: 10s
      timeout: 6s
      retries: 3

  report-harvester:
    build: ./services/report-harvester
    restart: always
    networks:
      - tradewise-net
    depends_on:
      database-api:
        condition: service_healthy
      mops-crawler:
        condition: service_healthy

  fugle-market-data:
    build: ./services/fugle-market-data
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net

  fugle-trading:
    build: ./services/fugle-trading
    restart: always
    env_file:
      - ./config/.env
    environment:
      - FUGLE_TRADING_CONFIG=/app/fugle-trading/config.simulation.ini
    volumes:
      - ./config/fugle-trading:/app/fugle-trading
    networks:
      - tradewise-net

  order-manager:
    build: ./services/order-manager
    restart: always
    networks:
      - tradewise-net

  insight-engine:
    build: ./services/insight-engine
    restart: always
    networks:
      - tradewise-net

  logging:
    build: ./services/logging
    restart: always
    networks:
      - tradewise-net

  database:
    image: mongo
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    volumes:
      - db-data:/data/db

  database-api:
    build: ./services/database-api
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    depends_on:
      - database
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import http.client; conn = http.client.HTTPConnection('localhost', 80); conn.request('GET', '/health'); response = conn.getresponse(); assert response.status == 200\""]
      interval: 10s
      timeout: 6s
      retries: 3

networks:
  tradewise-net:
    driver: bridge

volumes:
  db-data:
