version: '3.8'

services:
  telegram-bot:
    build: ./services/telegram-bot
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net

  twse-crawler:
    build: ./services/twse-crawler
    restart: always
    networks:
      - tradewise-net

  fugle-market-data:
    build: ./services/fugle-market-data
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net

  fugle-trading:
    build: ./services/fugle-trading
    restart: always
    volumes:
      - ./config/config.fugletrading.ini:/app/config.ini
      - ./config/cert.p12:/app/cert.p12
    networks:
      - tradewise-net

  order-manager:
    build: ./services/order-manager
    restart: always
    networks:
      - tradewise-net

  insight-engine:
    build: ./services/insight-engine
    restart: always
    networks:
      - tradewise-net

  logging:
    build: ./services/logging
    restart: always
    networks:
      - tradewise-net

  database:
    image: mongo
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    volumes:
      - db-data:/data/db

  database-api:
    build: ./services/database-api
    restart: always
    env_file:
      - ./config/.env
    networks:
      - tradewise-net
    depends_on:
      - database

networks:
  tradewise-net:
    driver: bridge

volumes:
  db-data:

